
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.*;
import javax.swing.JOptionPane;
/**
 * Clase que representa la interfaz para gestionar información de países.
 */
public class Paises extends javax.swing.JFrame {

	/**
     * Creates new form
     */
    public Paises() {
        initComponents();
    }
    
    //Envio de datos al servidor
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

        	
        	String mensaje = "Paises" + "-" + txtIdPais.getText() + "-" + txtDescPais.getText();  
            
            Socket socket = new Socket("192.168.1.2",9999);
            DataOutputStream salida = new DataOutputStream(socket.getOutputStream());    
           
            salida.writeUTF(mensaje);
                        
            DataInputStream entrada = new DataInputStream(socket.getInputStream());
            mensaje = entrada.readUTF();
            JOptionPane.showMessageDialog(null,"Resultado de la operacion : " + mensaje);
            
            socket.close();           
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Error : " +ex + " No se pudo realizar la conexión . ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
          
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	lblTitulo = new javax.swing.JLabel();    	
    	
        //jLabel1 = new javax.swing.JLabel();
        //jTextField1 = new javax.swing.JTextField();
        
        lblIdPais = new javax.swing.JLabel();
        txtIdPais = new javax.swing.JTextField();
        
        lblDescPais = new javax.swing.JLabel();
        txtDescPais = new javax.swing.JTextField();
        
        btnEjecutar = new javax.swing.JButton();
        
        //jButton1 = new javax.swing.JButton();
                

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Paises");
        lblIdPais.setText("Id");
        lblDescPais.setText("Pais");

        btnEjecutar.setText("Enviar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            
            .addGroup(layout.createSequentialGroup()
                
            		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    
            				.addGroup(layout.createSequentialGroup()
            						.addContainerGap()
            						.addComponent(lblIdPais))
            				
            				.addGroup(layout.createSequentialGroup()
            						.addContainerGap()
            						.addComponent(txtIdPais))  
            				
            				
            				
            				.addGroup(layout.createSequentialGroup()
            						.addContainerGap()
            						.addComponent(lblDescPais))
            				
            				.addGroup(layout.createSequentialGroup()
            						.addContainerGap()
            						.addComponent(txtDescPais))
                    
            				
            				
            				.addGroup(layout.createSequentialGroup()
            						.addGap(115, 115, 115)
            						.addComponent(lblTitulo)
            						.addGap(0, 0, Short.MAX_VALUE)))
                
            		.addContainerGap())
            
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                
                
                .addComponent(lblIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)     
                
                .addComponent(txtIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)                
                                
                
                .addComponent(lblDescPais, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)     
                               
                .addComponent(txtDescPais, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                
                                
                .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
            
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Cr<eate and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paises().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    
    private javax.swing.JLabel lblTitulo;
    
    private javax.swing.JLabel lblIdPais;
    private javax.swing.JTextField txtIdPais;
    
    private javax.swing.JLabel lblDescPais;
    private javax.swing.JTextField txtDescPais;
    
    private javax.swing.JButton btnEjecutar;
    
    /*private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;*/
    // End of variables declaration//GEN-END:variables

   
}
